replicaCount: 1

image:
  repository: docker.elastic.co/beats/elastic-agent
  tag: 8.9.2
  pullPolicy: IfNotPresent

fleetServer:
  enable: true
  elasticsearchHost: "<elasticsearch-host>"
  serviceToken: "<service-token>"
  policyID: "<fleet-server-policy>"

service:
  type: NodePort
  port: 8220

resources: {}

